# Generated by Django 3.2.9 on 2021-11-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report_Generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_fields',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
