# Generated by Django 3.2.8 on 2021-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_1', models.CharField(max_length=100)),
                ('password_2', models.CharField(help_text='Enter the same password as above, for verification.', max_length=100)),
                ('admin_Request', models.BooleanField()),
                ('admin_Key', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
