# Generated by Django 3.2.8 on 2021-10-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_siteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='admin_Key',
        ),
    ]
