# Generated by Django 3.2.8 on 2021-10-27 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_Tag', models.CharField(blank=True, default='No Tag', max_length=100)),
                ('purchase_Order_Number', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('iP_Address', models.CharField(blank=True, max_length=100)),
                ('spare_Inventory_Location', models.CharField(blank=True, max_length=100)),
                ('RMA', models.CharField(blank=True, default='No', max_length=100)),
                ('equipment_Name', models.CharField(blank=True, max_length=100)),
                ('equipment_Manufacturer', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('equipment_Type', models.CharField(blank=True, max_length=100)),
                ('tracking_Number', models.CharField(blank=True, max_length=100)),
                ('equipment_Model', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('serial_Number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('verizon_Cost_Center', models.CharField(blank=True, max_length=100)),
                ('attachments', models.FileField(blank=True, upload_to='')),
                ('additional_Specs', models.TextField(blank=True)),
                ('approval_Date', models.DateField(blank=True, null=True)),
                ('last_Audit_Date', models.DateField(default=django.utils.timezone.now)),
                ('purchase_Date', models.DateField(blank=True, null=True)),
                ('incident_Status', models.CharField(blank=True, max_length=100)),
                ('equipment_Issues', models.TextField(blank=True)),
                ('special_Notes', models.TextField(blank=True)),
                ('last_Modified', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
