# Generated by Django 3.2.9 on 2021-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryentry', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
