# Generated by Django 3.2.8 on 2021-10-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=32)),
                ('user_email', models.CharField(default='', max_length=32)),
                ('user_password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteToPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RequestUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_company', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=32)),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='date requested')),
                ('request_time', models.TimeField(default=django.utils.timezone.now, verbose_name='time requested')),
                ('request_id', models.IntegerField(default=0)),
                ('purchase_order', models.IntegerField(default=0)),
                ('equipment_name', models.CharField(max_length=32)),
                ('equipment_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=8)),
                ('requestee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date approved')),
                ('request', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Quote_Management.requestforquote')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('quote_name', models.CharField(default='', max_length=32)),
                ('equipment_name', models.CharField(default='', max_length=32)),
                ('quote_cost', models.IntegerField(default=0)),
                ('quote_quantity', models.IntegerField(default=0)),
                ('request', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Quote_Management.requestforquote')),
            ],
        ),
    ]
