# Generated by Django 3.2.8 on 2021-10-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Needs Asset Tag Confirmation', 'Needs Asset Tag Confirmation'), ('Pending', 'Pending'), ('Delivered/Clear', 'Delivered/Clear')], max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('Big Purchase', 'Big Purchase'), ('Small Purchase', 'Small Purchase'), ('Important Purchase', 'Important Purchase')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
