# Generated by Django 3.2.8 on 2021-10-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211024_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Big Purchase', 'Big Purchase'), ('Small Purchase', 'Small Purchase'), ('Important Purchase', 'Important Purchase')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='description',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='price',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
    ]
