# Generated by Django 3.2.9 on 2021-11-16 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_requests', '0009_auto_20211023_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('equipment_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_requests.equipmentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('po_number', models.CharField(default=' ', max_length=10)),
                ('product_id', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True)),
                ('vendor', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('unreviewed', 'unreviewed'), ('approved', 'approved'), ('rejected', 'rejected')], default='unreviewed', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('quote_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quote_manager.quoterequest')),
            ],
        ),
    ]
