# Generated by Django 3.2.8 on 2021-10-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='equip_name',
            new_name='equipment_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='equip_num',
            new_name='equipment_number',
        ),
        migrations.AlterField(
            model_name='request',
            name='ER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_requests.equipmentrequest'),
        ),
    ]
