# Generated by Django 3.2.8 on 2021-10-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0004_auto_20211023_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_requests.equipmentrequest'),
        ),
    ]
