# Generated by Django 3.2.8 on 2021-10-23 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0006_auto_20211023_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
