# Generated by Django 3.2.8 on 2021-10-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0007_equipmentrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='ER',
        ),
    ]
