# Generated by Django 3.2.8 on 2021-10-23 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0008_remove_request_er'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
